export const COUNTER_INCREAMENT = 'COUNTER_INCREAMENT';
export const COUNTER_DECREAMENT = 'COUNTER_DECREAMENT';
export const COUNTER_CLEAR = 'COUNTER_CLEAR';
export const COUNTER_SET = 'COUNTER_SET';
export const PRESSED_HELLO_BUTTON = 'PRESSED_HELLO_BUTTON';